INSERT INTO GENEROS(NOMBRE) VALUES ('Accion');
INSERT INTO GENEROS(NOMBRE) VALUES ('Suspenso');
INSERT INTO GENEROS(NOMBRE) VALUES ('Terror');
INSERT INTO GENEROS(NOMBRE) VALUES ('Fantasia');
INSERT INTO GENEROS(NOMBRE) VALUES ('Ciencia Ficcion');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Keanu Reeves', https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9Ht2WFi5ItkX_FgYO_Sc3PctjmcOSyo8YgUL7SRvh4T36CKXfVCMUrQImlAzCeY_xRqQ&usqp=CAU);
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Hugh Jackman',https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv8KLIqD5X5XBZXXHh5PNNq-MRZn2hWlgSaZRcnDWjj_INE2FecEl_IU3xZwhPFVIPbH0&usqp=CAU);
